name: Setup Python
description: Setup Python environment with Poetry

inputs:
  python-version:
    description: Python version
    required: false
    default: "3.10"
  no-root:
    description: Do not install package in the environment
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Install pipx
      run: |
        python -m pip install --user pipx
      shell: bash

    - name: Install poetry
      run: |
        pipx install poetry
      shell: bash
