name: Setup Python
description: Setup Python environment with Poetry

inputs:
  python-version:
    description: Python version
    required: false
    default: "3.10"
  no-root:
    description: Do not install package in the environment
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Install pipx
      run: |
        python -m pip install --user pipx
      shell: bash

    - name: Install poetry
      run: |
        pipx install poetry
      shell: bash

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: "poetry"
        cache-dependency-path: ./poetry.lock

    - run: |
        if [ "${{ inputs.no-root }}" = "true" ]; then
          poetry install --all-extras --no-root
        else
          poetry install --all-extras
        fi
      shell: bash
