name: Publish to TestPyPI

on:
  push:
    branches:
      - dev

jobs:
  publish:
    name: Publish Package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python environment
        uses: ./.github/actions/setup-python

      - name: Configure TestPyPI Repository
        run: poetry config repositories.testpypi https://test.pypi.org/legacy/

      - name: Set TestPyPI Token
        run: poetry config pypi-token.testpypi ${{ secrets.TEST_PYPI_TOKEN }}

      - name: Build Package for TestPyPI
        run: poetry build

      - name: Publish to TestPyPI
        run: poetry publish -r testpypi
