name: TestPyPI

on:
  push:
    tags:
      - "v*"
    branches:
      - dev

jobs:
  publish:
    name: Publish Package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python environment
        uses: ./.github/actions/setup-python

      - name: Clean build artifacts
        run: |
          rm -rf dist/
          rm -rf *.egg-info/

      - name: Build Package
        run: poetry build

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
