name: Publish to TestPyPI

on:
  workflow_run:
    workflows: ["NoneBot Plugin CI"]
    branches: [dev]
    types:
      - completed

jobs:
  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python environment
        uses: ./.github/actions/setup-python

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Configure TestPyPI Repository
        run: poetry config repositories.testpypi https://test.pypi.org/legacy/

      - name: Set TestPyPI Token
        run: poetry config pypi-token.testpypi ${{ secrets.TEST_PYPI_TOKEN }}

      - name: Build Package for TestPyPI
        run: poetry build

      - name: Publish to TestPyPI
        run: poetry publish -r testpypi
